// Build step: parse the vault -> src/data/kips.generated.json (consumed by the app).
import { writeFileSync, mkdirSync, readFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseVault } from "./parse-vault.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const vaultKips = resolve(here, "../../vault/KIPs");
const out = resolve(here, "../src/data/kips.generated.json");

const kips = parseVault(vaultKips);
mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, JSON.stringify(kips, null, 2) + "\n");
console.log(`build-kips: wrote ${kips.length} KIPs -> src/data/kips.generated.json`);

// Copy the semantic layer's related.json into the app's data dir (drives "Similar
// KIPs"). Committed artifact; regenerated by `cd viewer && npm run embeddings`.
// Missing file is non-fatal — the viewer just renders no Similar KIPs card.
const relatedSrc = resolve(here, "../../tools/semantic/related.json");
const relatedOut = resolve(here, "../src/data/related.generated.json");
if (existsSync(relatedSrc)) {
  writeFileSync(relatedOut, readFileSync(relatedSrc, "utf8"));
  console.log("build-kips: copied related.json -> src/data/related.generated.json");
} else {
  writeFileSync(relatedOut, "{}\n");
  console.warn(
    "build-kips: tools/semantic/related.json missing — wrote empty related.generated.json " +
      "(run `cd viewer && npm run embeddings` to generate)"
  );
}
