// Build step: parse the vault -> static JSON artifacts under viewer/public/data/.
//
// These are *fetched at runtime*, never imported by the app, so the KIP corpus
// stays out of the JS bundle (docs/sync-strategy.md §6: shipped JS must stay
// well under ~300KB gzip; at 1144 KIPs an inlined corpus pushed it to ~470KB).
//
//   public/data/index.json      compact one-line-per-KIP list -> Browse + filters
//   public/data/kips/<id>.json  full Kip object -> Detail (fetched on demand)
//   public/data/related.json    semantic neighbor map -> "Similar KIPs"
//
// Vite copies public/ verbatim into dist/, so the CDN caches each file
// independently and a visitor only downloads the KIPs they actually open.
import { writeFileSync, mkdirSync, readFileSync, existsSync, rmSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseVault } from "./parse-vault";
import type { Kip } from "../src/types";

/** Max blurb length; KIP cards only render ~3 lines, so anything more is waste. */
export const BLURB_MAX = 180;

/** The compact per-KIP record shipped in index.json (mirrors src/lib/kips.ts). */
export interface KipIndexEntry {
  id: string;
  title: string;
  status: Kip["status"];
  category: string;
  release: string;
  tags: string[];
  blurb: string;
  stub?: boolean;
}

/** Collapse whitespace and cut to <= BLURB_MAX chars on a word boundary. */
export function blurbOf(summary: string, max = BLURB_MAX): string {
  const flat = summary.replace(/\s+/g, " ").trim();
  if (flat.length <= max) return flat;
  const cut = flat.slice(0, max);
  const sp = cut.lastIndexOf(" ");
  return (sp > max * 0.5 ? cut.slice(0, sp) : cut).replace(/[,;:.\-–—]+$/, "") + "…";
}

export function indexEntry(k: Kip): KipIndexEntry {
  const e: KipIndexEntry = {
    id: k.id,
    title: k.title,
    status: k.status,
    category: k.category,
    release: k.release,
    tags: k.tags,
    blurb: blurbOf(k.summary),
  };
  if (k.stub) e.stub = true;
  return e;
}

export function buildData(kips: Kip[], outDir: string, relatedSrc: string): void {
  // Start clean so KIPs deleted from the vault don't linger as stale detail files.
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(join(outDir, "kips"), { recursive: true });

  writeFileSync(join(outDir, "index.json"), JSON.stringify(kips.map(indexEntry)));
  for (const k of kips) writeFileSync(join(outDir, "kips", `${k.id}.json`), JSON.stringify(k));

  // Committed artifact from the semantic layer; regenerated by `bun run embeddings`.
  // Missing file is non-fatal — the viewer just renders no Similar KIPs card.
  if (existsSync(relatedSrc)) {
    writeFileSync(join(outDir, "related.json"), readFileSync(relatedSrc, "utf8"));
  } else {
    writeFileSync(join(outDir, "related.json"), "{}\n");
  }
}

// Executed as a script (predev/prebuild); importable for tests without side effects.
const selfPath = fileURLToPath(import.meta.url);
if (process.argv[1] && resolve(process.argv[1]) === selfPath) {
  const here = dirname(selfPath);
  const kips = parseVault(resolve(here, "../../vault/KIPs"));
  const outDir = resolve(here, "../public/data");
  const relatedSrc = resolve(here, "../../tools/semantic/related.json");
  const hadRelated = existsSync(relatedSrc);

  buildData(kips, outDir, relatedSrc);
  console.log(
    `build-kips: wrote public/data/index.json (${kips.length} entries) + ` +
      `public/data/kips/*.json (${kips.length} files)`
  );
  console.log(
    hadRelated
      ? "build-kips: copied related.json -> public/data/related.json"
      : "build-kips: tools/semantic/related.json missing — wrote empty public/data/related.json " +
          "(run `cd viewer && bun run embeddings` to generate)"
  );
}
